"""add city and job tables

Revision ID: 324ffdd965a3
Revises: 
Create Date: 2026-03-06 17:07:47.782085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '324ffdd965a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first (skill_trends depends on skills, job_skills depends on skills/jobs)
    op.drop_table('skill_trends')
    op.drop_table('job_skills')

    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_metric_name'))

    op.drop_table('trend_snapshots')
    op.drop_table('tools')
    op.drop_table('profile_tasks')
    op.drop_table('profile_skills')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))

    op.drop_table('skills')
    op.drop_table('profile_tools')
    op.drop_table('risk_scores')
    op.drop_table('profile_aspirations')
    with op.batch_alter_table('skill_intel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_intel_created_at'))
        batch_op.drop_index(batch_op.f('ix_skill_intel_skill_name'))
        batch_op.drop_index(batch_op.f('ix_skill_intel_timeframe'))

    op.drop_table('skill_intel')
    op.drop_table('worker_profiles')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_column('message_json')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_cities_name'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('job_ai_vulnerabilities', schema=None) as batch_op:
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_job_ai_vulnerabilities_computed_at'))
        batch_op.drop_index(batch_op.f('ix_job_ai_vulnerabilities_job_role'))
        batch_op.create_index(batch_op.f('ix_job_ai_vulnerabilities_job_role'), ['job_role'], unique=True)
        batch_op.drop_column('source')
        batch_op.drop_column('model_version')
        batch_op.drop_column('factors_json')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('posted_date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='posted_date::date')
        batch_op.alter_column('scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('jobs_job_url_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('jobs_scrape_run_id_fkey'), type_='foreignkey')
        batch_op.drop_column('experience')
        batch_op.drop_column('scraped_keyword')
        batch_op.drop_column('job_url')
        batch_op.drop_column('company')
        batch_op.drop_column('scrape_run_id')
        batch_op.drop_column('location')

    # Now safe to drop scrape_runs after FK removed from jobs
    op.drop_table('scrape_runs')

    with op.batch_alter_table('processed_user_outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_processed_user_outputs_output_type'))
        batch_op.create_index(batch_op.f('ix_processed_user_outputs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_user_outputs_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_user_outputs_job_title'), ['job_title'], unique=False)
        batch_op.drop_column('input_json')
        batch_op.drop_column('model_version')
        batch_op.drop_column('output_type')
        batch_op.drop_column('output_json')
        batch_op.drop_column('source')
        batch_op.drop_column('model_name')

    with op.batch_alter_table('reskilling_plans', schema=None) as batch_op:
        batch_op.alter_column('plan_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_reskilling_plans_created_at'))
        batch_op.drop_column('selected_skills_json')
        batch_op.drop_column('created_by')
        batch_op.drop_column('roadmap_json')

    with op.batch_alter_table('roadmap_week_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_objective', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_roadmap_week_items_week_number'))
        batch_op.drop_column('details_json')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('education')
        batch_op.drop_column('preferences_json')
        batch_op.drop_column('profile_json')
        batch_op.drop_column('phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferences_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('education', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('roadmap_week_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_roadmap_week_items_week_number'), ['week_number'], unique=False)
        batch_op.drop_column('learning_objective')

    with op.batch_alter_table('reskilling_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selected_skills_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_reskilling_plans_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('plan_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('processed_user_outputs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('output_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('output_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('model_version', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('input_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_processed_user_outputs_job_title'))
        batch_op.drop_index(batch_op.f('ix_processed_user_outputs_domain'))
        batch_op.drop_index(batch_op.f('ix_processed_user_outputs_city'))
        batch_op.create_index(batch_op.f('ix_processed_user_outputs_output_type'), ['output_type'], unique=False)
        batch_op.drop_column('domain')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('city')
        batch_op.drop_column('job_title')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scrape_run_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('job_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scraped_keyword', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('jobs_scrape_run_id_fkey'), 'scrape_runs', ['scrape_run_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('jobs_job_url_key'), ['job_url'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('posted_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('job_ai_vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factors_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_job_ai_vulnerabilities_job_role'))
        batch_op.create_index(batch_op.f('ix_job_ai_vulnerabilities_job_role'), ['job_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_ai_vulnerabilities_computed_at'), ['computed_at'], unique=False)
        batch_op.alter_column('risk_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)
        batch_op.alter_column('state',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)

    op.create_table('job_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_skills_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_skills_pkey'))
    )
    op.create_table('worker_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('normalized_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('city_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('writeup', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inferred_domain', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('worker_profiles_city_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('worker_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_profiles_pkey'))
    )
    op.create_table('skill_trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('demand_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('skill_trends_city_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('skill_trends_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_trends_pkey'))
    )
    op.create_table('skill_intel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('demand_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('growth_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('salary_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ai_relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('intelligence_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_intel_pkey'))
    )
    with op.batch_alter_table('skill_intel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_intel_timeframe'), ['timeframe'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_intel_skill_name'), ['skill_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_intel_created_at'), ['created_at'], unique=False)

    op.create_table('profile_aspirations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aspiration', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['worker_profiles.id'], name=op.f('profile_aspirations_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_aspirations_pkey'))
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('jobs_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scrape_runs_pkey'))
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('factors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('risk_scores_city_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_scores_pkey'))
    )
    op.create_table('profile_tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['worker_profiles.id'], name=op.f('profile_tools_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_tools_pkey'))
    )
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('skills_pkey'))
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('profile_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('match_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['worker_profiles.id'], name=op.f('profile_skills_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_skills_pkey'))
    )
    op.create_table('profile_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_description', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['worker_profiles.id'], name=op.f('profile_tasks_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_tasks_pkey'))
    )
    op.create_table('tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tools_pkey')),
    sa.UniqueConstraint('name', name=op.f('tools_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trend_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('trend_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trend_snapshots_pkey'))
    )
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_snapshots_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
